// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/jatek-screens/Earnings.tsx": () => import("../components/mockups/jatek-screens/Earnings.tsx"),
  "./components/mockups/jatek-screens/Home.tsx": () => import("../components/mockups/jatek-screens/Home.tsx"),
  "./components/mockups/jatek-screens/Login.tsx": () => import("../components/mockups/jatek-screens/Login.tsx"),
  "./components/mockups/jatek-screens/Orders.tsx": () => import("../components/mockups/jatek-screens/Orders.tsx")
};
